Try putting R functions in separate script
microbiomedata/nmdc_notebooks pull request #103
Opened 2024-12-10 19:33 UTC by bmeluch

Testing if we can pull the R API functions out of notebooks and define them all in a single R script, so we aren't accidentally defining the same function with different tweaks in different notebooks.

Eventually this may become an R package, but R scripts seem to play nicer than R packages when embedded in a repo.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/microbiomedata/nmdc_notebooks/blob/main/.github/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/microbiomedata/nmdc_notebooks/pulls) for the same update/change?
* [x] Does your PR link to an issue?
* [ ] Have you described the changes this PR will make?

### Notebook Fix Submissions:

* [ ] Does your PR include links to the updated notebook **(in the branch)** for review using [nbviewer](https://nbviewer.jupyter.org/), [Colab](https://colab.research.google.com/), and [reviewnb](https://www.reviewnb.com/)? These three are the preferred ways to review changes and additions to notebooks during review.

2025-01-15 16:52 UTC, kheal requested changes

2025-01-15 16:52 UTC, kheal commented on utility_functions.R
> +get_next_results <- function(collection, filter_text, max_page_size, fields) {
You might consider renaming this function to something like `get_all_results` because that's actually what it's doing (not just getting the next ones).

2025-01-15 16:52 UTC, kheal commented on utility_functions.R
> +get_first_page_results <- function(collection, filter, max_page_size, fields) {
Consider adding roxygen annotations for each function that describes the parameters.  https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html .  This helps with auto completion and is generally the best practice for documenting functions in R.

2025-01-15 16:52 UTC, kheal commented on utility_functions.R
> +    # id_list: a list of ids to filter on
Are these actually R lists or are they vectors?  I think vectors?

2025-01-15 16:52 UTC, kheal commented on utility_functions.R
> +            max_page_size = max_id*3, #assumes that there are no more than 3 records per query
Remove this *3 and associated comment, they aren't true.  Consider adding the max_page_size parameter to this function.

2025-01-15 16:52 UTC, kheal commented on taxonomic_dist_by_soil_layer/R/taxonomic_dist_soil_layer_R.ipynb
>     "cell_type": "code",
<p>The text for part 2 is rendering oddly - see above.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/microbiomedata/nmdc_notebooks/pull/103/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2025-01-15 16:52 UTC, kheal commented on taxonomic_dist_by_soil_layer/R/taxonomic_dist_soil_layer_R.ipynb
>     "cell_type": "code",
<p>Same comment at re: Step 2 </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/microbiomedata/nmdc_notebooks/pull/103/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2025-01-15 16:52 UTC, kheal commented on taxonomic_dist_by_soil_layer/R/taxonomic_dist_soil_layer_R.ipynb
>     "cell_type": "code",
<p>Oops, we reference "omics processing" here - please change to data generation</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/microbiomedata/nmdc_notebooks/pull/103/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2025-01-15 16:52 UTC, kheal commented on taxonomic_dist_by_soil_layer/R/taxonomic_dist_soil_layer_R.ipynb
>     "cell_type": "code",
<p>Text rendering oddly in step 7</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/microbiomedata/nmdc_notebooks/pull/103/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='35'/>

2025-01-15 16:52 UTC, kheal commented on taxonomic_dist_by_soil_layer/R/taxonomic_dist_soil_layer_R.ipynb
>     "cell_type": "code",
<p>Text rendering oddly in previous chunk</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/microbiomedata/nmdc_notebooks/pull/103/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='49'/>

2025-01-15 18:07 UTC, kheal commented
@bmeluch - the sourcing for the functions doesn't work in google colab.

Here's a link to the NOM notebook in this branch in google colab - it'd be good to have this in the PR description because this is something we should be testing during each new notebook.  When I try to run the first cell, it errors out with the new sourcing.  I'm pretty sure @samobermiller had figured out a workaround for the python functions to make this work, hopefully the same will work for R?  

NOM notebook in colab:
https://colab.research.google.com/github/microbiomedata/nmdc_notebooks/blob/90-modularize-r-api-wrapper-functions/NOM_visualizations/R/NOM_R_notebook.ipynb

Taxonomy notebook in colab:
https://colab.research.google.com/github/microbiomedata/nmdc_notebooks/blob/90-modularize-r-api-wrapper-functions/taxonomic_dist_by_soil_layer/R/taxonomic_dist_soil_layer_R.ipynb

2025-01-31 00:58 UTC, bmeluch commented on utility_functions.R
> +get_first_page_results <- function(collection, filter, max_page_size, fields) {
I agree but since we aren't making this into its own package yet, I'm not sure I want to drop a bunch of .Rd files in this repo. Future improvement?

2025-01-31 23:35 UTC, bmeluch commented
The R script sourcing in Colab should work now (thank you for the links @kheal ! )
Some of the weird formatting in the taxonomy notebook is fixed, but not all -  I really don't know what's going on there since it only looks weird in ReviewNB, but I'll keep trying.
This PR is temporarily blocked on re-rendering the taxonomy notebook once NERSC is back up next week.

2025-02-01 01:18 UTC, kheal commented
@bmeluch 
You should be able use nbviewer to look at your branches version (consider linking them in the PR like the colab links).  If the rendering on nbviewer (what we link to in the readme) looks fine, don't worry about the formatting.  I can imagine the ReviewNB view can make things a bit wonky sometimes.  Please re-request a review when you're ready and I'll check things over again.

2025-02-11 04:40 UTC, bmeluch commented
Both notebooks have been rerendered and are passing checks

NOM: Looks good in Github, nbviewer, Colab, and ReviewNB as far as I can see.

Taxonomy: Looks good in Github and Colab, text is weird in ReviewNB as noted, plots are weird in nbviewer. A mystery.

2025-02-11 19:36 UTC, samobermiller approved these changes
Everything was generating fine for me other than the previously listed caveats in nbviewer!

2025-02-11 21:05 UTC, kheal commented
huzzah!  LGTM.  Just make sure to change the link to the main branch in the first cell after it's been merged in - I forget the order of operations that @samobermiller had to do this, but I trust you two can figure it out.

2025-02-11 21:05 UTC, kheal approved these changes

2025-02-11 21:34 UTC, merged